name: Windows build

on:
  push:
  pull_request:
    branches: [master]

jobs:

  test:
    strategy:
      matrix:
        os: ['windows-latest']
        node-version: [16.x, 18.x]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        shell: bash
      - run: npm run test
        shell: bash        
     
